# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_entities = QtWidgets.QWidget()
        self.tab_entities.setObjectName("tab_entities")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab_entities)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.entitiesListView = QtWidgets.QListView(parent=self.tab_entities)
        self.entitiesListView.setObjectName("entitiesListView")
        self.horizontalLayout.addWidget(self.entitiesListView)
        self.tabWidget.addTab(self.tab_entities, "")
        self.tab_transitions = QtWidgets.QWidget()
        self.tab_transitions.setObjectName("tab_transitions")
        self.tabWidget.addTab(self.tab_transitions, "")
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuEmulator = QtWidgets.QMenu(parent=self.menubar)
        self.menuEmulator.setObjectName("menuEmulator")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConnect = QtGui.QAction(parent=MainWindow)
        self.actionConnect.setObjectName("actionConnect")
        self.actionQuit = QtGui.QAction(parent=MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.menuEmulator.addAction(self.actionConnect)
        self.menuEmulator.addSeparator()
        self.menuEmulator.addAction(self.actionQuit)
        self.menubar.addAction(self.menuEmulator.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tomba! Tools"))
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_entities),
            _translate("MainWindow", "Entities"),
        )
        self.tabWidget.setTabText(
            self.tabWidget.indexOf(self.tab_transitions),
            _translate("MainWindow", "Transitions"),
        )
        self.menuEmulator.setTitle(_translate("MainWindow", "Emulator"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
